### ISSUE TITLE
Crash ? (Issue with Garena league)

### ISSUE THREAD

**Issue by nguyenvancaoky** [LoL-Fantome/Fantome#11]
I have problem.
https://i.imgur.com/XyqoN1F.gifv
after select LeagueLocation.

**Comment by Crauzer** [comment]
Send me the content of your League folder.
Try deleting the DATABASE file and Overlay folder

**Comment by nguyenvancaoky** [comment]
League folder
https://i.imgur.com/LpJb3Ja.gifv

**Comment by Crauzer** [comment]
Is that garena ?
Fantome won't work. It needs to have the Game folder inside the main League folder.

**Comment by nguyenvancaoky** [comment]
yes, garena

**Comment by Crauzer** [comment]
I will add support for this soon. I guess you can't use Fantome for now

**Comment by nguyenvancaoky** [comment]
I see. Thank you

**Comment by Virace** [comment]
Oh, that's a good thing.

**Comment by GzPhantom** [comment]
@Virace dalao!

**Comment by Virace** [comment]
@GzPhantom mutual learning

**Comment by Crauzer** [comment]
@Virace @nguyenvancaoky Are you able to test a version that should support Garena ?

**Comment by Crauzer** [comment]
https://drive.google.com/file/d/1ESROSWKUu5SIPIJYXRL0Moe2iJ6-nr_v/view?usp=sharing

**Comment by Virace** [comment]
> https://drive.google.com/file/d/1ESROSWKUu5SIPIJYXRL0Moe2iJ6-nr_v/view?usp=sharing

Ok, let me try

**Comment by Crauzer** [comment]
So does it work ?

**Comment by Virace** [comment]
> So does it work ?

Well, It looks good.
[Imgur](https://i.imgur.com/EpvIQcy.png)
[Imgur](https://i.imgur.com/AaFyOji.png)

**Comment by Crauzer** [comment]
niceee, this means Garena is working.
Thank you very much <3

**Comment by DUA0204** [comment]
Im also the Garena folder，but im TW server.
and I tried ....[https://drive.google.com/file/d/1ESROSWKUu5SIPIJYXRL0Moe2iJ6-nr_v/view?usp=sharing](url) but It doesn't work for me.... when I add some mod and go ingame test,It just doesn't change anything...
btw It's loading too fast like it didn't actually load any file.

**Comment by Crauzer** [comment]
that's probably because the Mod is not correctly made

**Comment by paiyantmgn** [comment]
> 
> 
> that's probably because the Mod is not correctly made

Can confirm, it doesn't work for me either. Here are the skins I tested with. It installs without any issue but nothing changes in-game.
![www](https://user-images.githubusercontent.com/37238471/72159151-f63de400-33e5-11ea-9e52-729579a7b677.PNG)

**Comment by Crauzer** [comment]
Can you send the path that fantome is located in ?

**Comment by paiyantmgn** [comment]
> 
> 
> Can you send the path that fantome is located in ?
> Because I've had multiple people confirm that Fantome works on Garena.

Running Fantome as administrator seems to have fixed the issue. 
My bad for the confusion.

**Comment by Crauzer** [comment]
Okay, can you check if league is running in admin mode ?
Check if any of the league executables have admin privilages.

**Comment by paiyantmgn** [comment]
![image](https://user-images.githubusercontent.com/37238471/72160871-48343900-33e9-11ea-848e-db67c95df5d0.png)
All four of these are running in admin mode.

**Comment by DUA0204** [comment]
well...i think its still doesn't work for me,even if running Fantome as administrator.

**Comment by Crauzer** [comment]
Yeah that's the issue then I guess.
I will add proper admin privilages removal  in Fantome 1.0

**Comment by Crauzer** [comment]
@DUA0204 Try removing admin privilages from all league executables

**Comment by DUA0204** [comment]
ok,let me try..

**Comment by DUA0204** [comment]
still not work

> @DUA0204 Try removing admin privilages from all league executables

stll not work...

**Comment by DUA0204** [comment]
![folder01](https://user-images.githubusercontent.com/59332411/72162842-a10dcc80-33fd-11ea-8c8c-1f6bb0a8a975.JPG)
![folder02](https://user-images.githubusercontent.com/59332411/72162843-a10dcc80-33fd-11ea-96c5-a1191190e1e9.JPG)
![folder03](https://user-images.githubusercontent.com/59332411/72162845-a1a66300-33fd-11ea-88de-be1957ac3c4d.JPG)

**Comment by Crauzer** [comment]
Where is your Fantome folder located

**Comment by Crauzer** [comment]
Make sure that the path to Fantome does not contain any Chinese or similar characters

**Comment by DUA0204** [comment]
this is my Fantome folder located
![擷取](https://user-images.githubusercontent.com/59332411/72167274-cf8fa580-3405-11ea-9c00-3456e4fc94ed.JPG)
mybe there is some issue in my own computer,but still thanks for your help<3.
I will find the problem myself

**Comment by Crauzer** [comment]
This is not your fantome folder....
That's your league folder. I asked for the folder you extracted Fantome to.
If the path to the Fantome folder contains any chinese characters you need to move it to a path that doesn't

**Comment by DUA0204** [comment]
![擷取](https://user-images.githubusercontent.com/59332411/72171899-d66ee600-340e-11ea-8f88-46a1f99403cb.JPG)
ohh, i work!!!!! so so thanks!!  i just change my user name「段」to duan 
and it work!!<3  Sorry for bothering you , very thanks to you~
