### ISSUE TITLE
Game will not connect while Fantome is running

### ISSUE THREAD

**Issue by wolffang719** [LoL-Fantome/Fantome#46]
I'm not sure what happened; I played at least a dozen games with Fantome running and custom skins just fine but then one game after champion select it told me there was an issue with my game installation, I think I tried to load to many skins at once as I had tried to do more then three for the first time this game so after League fixed itself I tried running Fantome again but now after champion select the client reopens with the 'reconnect' button and unless I close Fantome it won't play but then I have no custom skins.
I tried using Fantome's setting and rerouting it to the League Game folder, I tried restarting my pc, I don't really understand whats going wrong..

**Comment by hihiniki** [comment]
I have the same issue and i tried to ask in the discord support chat but everyone seems to be ignoring my question..

**Comment by Crauzer** [comment]
Delete the Overlay folder, MOD_DATABASE file and INDEX file.
