### ISSUE TITLE
The mods i have activated doesnt work in League of Legends

### ISSUE THREAD

**Issue by Mukade1234** [LoL-Fantome/Fantome#48]
Hey,

I installed different mods for League of Legends like an announcer some skins and a different map.
They doesnt appear in the matches. The joke about the thing is yesterday worked everything fine and today nothing worked. I tried some thing like delete the overlay folder....  and the other one. I also deinstalled league of legends and then installed lol again. Nothing fixed my problem. I also tried to reinstall Fantome nothing helped. 
I hope u can help to fix this Problem.
I like the this application and wnat to use different announcer.

**Comment by Crauzer** [comment]
Try launching Fantome as admin
