### ISSUE TITLE
League crashes after champ select 

### ISSUE THREAD

**Issue by Kungfupacman** [LoL-Fantome/Fantome#55]
Champ loading screen will rapidly load to 100% and crash over and over until I close Fantome, after game has started I can close client and reopen Fantome, but will get high latency until I close Fantome and reset client.

**Comment by Crauzer** [comment]
Care to elaborate? 
What mods are you using?

**Comment by yassuoking** [comment]
I can not use it.It sill&nbsp;report errors while I run the program. I've already uninstalled it.But I am using another one.
My English is not very good.I hope you can understand me.
PS：My favorite heroes is Zed and Yasuo.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LoL-Fantome/Fantome"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午4:55
收件人:&nbsp;"LoL-Fantome/Fantome"<Fantome@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [LoL-Fantome/Fantome] League crashes after champ select  (#55)





 
Care to elaborate?
 What mods are you using?

**Comment by Crauzer** [comment]
League crashes are usually caused by outdated mods.

**Comment by Crauzer** [comment]
I can test the mods you're using if you send them.

**Comment by TheKillerey** [comment]
First use the tool without mods to make sure it's the mod and not Fantome

**Comment by yassuoking** [comment]
I know it. It will report errors when I just double-click on the software.I guess the reason that I select a wrong folder because the folder come from China.Now,I using another software that is similar to Fantome.







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Crauzer"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 下午5:22
收件人: "LoL-Fantome/Fantome"<Fantome@noreply.github.com&gt;; 
抄送: "於烬炎"<2411907606@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [LoL-Fantome/Fantome] League crashes after champ select  (#55)





 
League crashes are usually caused by outdated mods.

**Comment by Crauzer** [comment]
Fantome will most likely not work with the Chinese Game client, afaik it is coded differently.

**Comment by yassuoking** [comment]
Obsidian is very nice.I can edit my LOL by using it.It is so really cool. Thank you very much!







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Crauzer"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 晚上6:27
收件人: "LoL-Fantome/Fantome"<Fantome@noreply.github.com&gt;; 
抄送: "於烬炎"<2411907606@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [LoL-Fantome/Fantome] League crashes after champ select  (#55)





 
Fantome will most likely not work with the Chinese Game client, afaik it is coded differently.

**Comment by Kungfupacman** [comment]
I am using an old aatrox skin mod, it was working fine the first few days but now the issue appears inconsistently. Link to mod below. 

https://gofile.io/d/GLeJnn

**Comment by Crauzer** [comment]
> I am using an old aatrox skin mod, it was working fine the first few days but now the issue appears inconsistently. Link to mod below.
> 
> https://gofile.io/d/GLeJnn

Look at issue #56
