### ISSUE TITLE
Game loading freezing at 60 %

### ISSUE THREAD

**Issue by Bufito** [LoL-Fantome/Fantome#69]
When I have mods activated an error occurs at around 58-60% of the game loading in loading screen. A message of a "Fatal Error" appears and League crashes. Pls fix this before ARURF ends, I need to play with Shaggy Ryze to experience Shaggy's power at 0,01%!

**Comment by Bufito** [comment]
Update: I've tried using different skins and get the same problem so this is not because the skin is outdated.

**Comment by Bufito** [comment]
Update 2: I joined the Discord server and found out from the support channel that all skins made before this patch are actually outdated because riot dropped support for legacy skeletons and that a tool will probably be created that will update our custom skins to the new supported version at some point!

**Comment by Morilli** [comment]
you could update your mods manually using https://github.com/Morilli/LeagueToolkit/releases/tag/0.1

**Comment by Bufito** [comment]
I'm not that advanced so could you explain to me how to update the mods manually? I didn't find any .skl files in the fantome custom skin I downloaded and want to update so it's probably more complicated than dragging and dropping the custom skin to the LeagueToolkit.

**Comment by Morilli** [comment]
There are modding discords like voxskins where you can find help for this specific issue. One video that was made for it is https://youtu.be/NSmFuqGelHw. 

I'll close this issue as this issue has nothing to do with fantome directly, but rather with mods using incorrect files and the game not loading cause of them.

**Comment by Bufito** [comment]
Okay. Thanks a lot for your help and for making and maintaining this program, I really appreciate it!
