### ISSUE TITLE
When will it be released?

### ISSUE THREAD

**Issue by beastzy** [LoL-Fantome/Fantome#7]
i am waiting anxiously for this program, i hope it doesnt give the same error as wooxy. the error was failed to locate lol.launcher.exe, because these files arent in the directory anymore

**Comment by ChewyBomber** [comment]
I'm gonna fix this bug in Wooxy soon so you don't have to wait for Fantome to install your favorite skins.

**Comment by beastzy** [comment]
What a relief to here this from you chewy, I thought wooxy was dead, cuz even in the new elite version this was happening to me

**Comment by quagzy** [comment]
will this work with garena as well?

**Comment by Crauzer** [comment]
Most likely
