### ISSUE TITLE
Fantome crashes league on game start

### ISSUE THREAD

**Issue by Katakirauwa** [LoL-Fantome/Fantome#73]
Whenever I load a game with fantome open my game stays at 0% then crashes saying it needs to fix league and reinstall then trys to load the game again and repeats. Anyone have a fix?

**Comment by Morilli** [comment]
Fantome is currently not supported to use league mods with. Use [lcs-manager](https://github.com/LoL-Fantome/lolcustomskin-tools/releases) instead.
